<template>
  <div>
    <iframe
      width="100%"
      height="1000px"
      src="https://www.youtube.com/embed/O91DT1pR1ew?autoplay=1"
      frameborder="0"
      allow="autoplay"
      allowfullscreen
    ></iframe>
  </div>
</template>